### ISSUE TITLE
Negative flux in pixel not allowed in extended sources

### ISSUE THREAD

**Issue by zhoouhaoo** [giacomov/astromodels#24]
L182 in sources/extended_sources.py, "return np.maximum(result, 1e-60)", sets the flux in a pixel to almost 0 when it is negative. It caused the problem Andrea saw, i.e. all same logL when flux <=0, which may skew the uncertainty calculation.

I know this is to avoid some problems with extremely small values. Can we change the requirement on absolute values? For example, "return np.maximum(result, 1e-60) if result>=0 else np.minimum(result, -1e-60)". It may not work as result is an array but something like that.

**Comment by giacomov** [comment]
good catch!

When I coded this I assumed we were never going to use "negative sources". I am more for removing that line altogether and just return the "result" array as is.

**Comment by physics-andrea** [comment]
I switch that line to "return result" as suggested by Giacomo and that seems to fix the profile logLikelihood.  

We'll want the option to go negative for dark matter searches since often the background in the ROI has a negative fluctuation and its useful to be able to allow the signal piece to go negative to study systematics and get the errors correctly.
