### ISSUE TITLE
Log Normal prior Negative values

### ISSUE THREAD

**Issue by cbrisboi** [giacomov/astromodels#67]
The log_normal distribution in `priors.py` lets negative values get evaluated in the np.log() function.
Despite adding bounds to a parameter in the model specification, emcee kinda does its own thing and tries negative flux values when the prior is non-zero. The prior for a log normal then returns -np.inf. Naively to me, the behavior should be that for negative x the log_normal distribution would return 0. 

Adding these lines
`if x_ <=0:
            return 0`
seems to fix the issue. 

I did not submit a pull request because there is an additional units question to consider that should be decided upon for the best way to address the problem.

**Comment by henrikef** [comment]
It actually returns `np.nan` , which causes problems later on (emcee assumes that unless the prior is `0`, the value is technically allowed, and tries to set the parameter to that value. That can lead it to try to set e.g.  the normalization constant of a power law to a negative value, which causes problems due to the internal log transform.

**Comment by giacomov** [comment]
I fixed this and closed the issue. Please reopen if you have further problem.
